#!/bin/bash
## Get the current frequency, display a gauge icons (nerd font) accordingly.


icons=( '󰡳' '󰡵' '󰊚' '󰡴' '?' )

set -euo pipefail

getFreq() {

	freq_sum=0

	nproc=$(( $(nproc) -1 ))

	for ncpu in $( seq 0 $nproc ); do

		cpufreq=$( < "/sys/devices/system/cpu/cpu$ncpu/cpufreq/scaling_cur_freq" )

		freq_sum=$(( freq_sum + cpufreq ))

	done

	cur_freq=$(( $(( $freq_sum / $(nproc) )) / 1000 ))

}


defineThreshold() {

	sleep_freq='800'
	low_freq='1600'
	high_freq='2300'
	full_freq='2900'

	if (( $cur_freq >= $full_freq )); then

		echo "${icons[3]}"

	elif (( $cur_freq >= $high_freq )); then

		echo "${icons[2]}"

	elif (( $cur_freq >= $low_freq )); then

		echo "${icons[1]}"

	elif (( $cur_freq >= $sleep_freq )); then

		echo "${icons[0]}"

	fi

}

main() {

	getFreq
	defineThreshold

}

main
