#!/bin/bash
## Get the current ram usage, display a gauge icons (nerd font) accordingly.

total_ram=$(free -m | awk '/Mem:/ {print $2}')
available_ram=$(free -m | awk '/Mem:/ {print $7}')
ram_used=$((100 - available_ram * 100 / total_ram))
icons=( '' '' '' '' '' '?' )


case $ram_used in

        ## 0 -> 20%
        [0-9]|1[0-9]|20)
                icon="${icons[0]}"
				echo $icon
                ;;

        ## 21 -> 39%
        [2][1-9]|3[0-9])
                icon="${icons[1]}"
				echo $icon
                ;;

        ## 40 -> 59%
        [4][0-9]|5[0-9])
                icon="${icons[2]}"
				echo $icon
                ;;

        ## 60 -> 79%
        [6][0-9]|7[0-9])
                icon="${icons[3]}"
				echo $icon
                ;;

        ## 80 -> 100%
        [8][0-9]|9[0-9]|100)
                icon="${icons[4]}"
				echo $icon
                ;;

        ## unknown %
        *)
                icon="${icons[5]}"
				echo $icon
				exit 1
                ;;

esac
