#!/bin/bash
## Get the current ram usage %

getRamTotal() {

	ram_type=( $( free | grep -E 'Mem|Swap' | awk '{print $2}' ) )
	sum=0

	for r_type in "${ram_type[@]}"; do
		sum=$((${r_type} + ${sum}))
	done

	ram_total=${sum}

}

getRamUsed() {

	ram_type=( $( free | grep -E 'Mem|Swap' | awk '{print $3}' ) )
	sum=0

	for r_type in "${ram_type[@]}"; do
		sum=$((${r_type} + ${sum}))
	done

	ram_used=${sum}

}

main() {

	getRamUsed
	getRamTotal

	r_ratio=$(echo "${ram_used} / ${ram_total}"|bc -l)
	r_usage=$(echo "0$r_ratio * 100"|bc -l)

#	printf '%.2f%%' "$r_usage"
	printf '%.f%%' "$r_usage"

}

main
