#!/bin/bash
## Get the current temperature, display an emoji icons accordingly.

#icons=( '🧊' '🥶' '😎' '🥵' '🔥' '?' )
icons=( '' '' '' '' '' )

temp_crit=$(
	sensors \
		| grep 'crit' \
		| awk '{print $9}' \
		| cut -d '.' -f 1 \
		| sort -u \
		| tac \
		| tr -d '+' \
		| head -n 1
)

temp_freeze='0'

temp_high=$( echo "${temp_crit} / 1.5" | bc )
temp_normal=$(( "${temp_crit}" / 2 ))
temp_low=$( echo "${temp_crit} / 3" | bc )

sensor='temp1'

temp=$(
	sensors \
		| grep "${sensor}" \
		| awk {'print $2'} \
		| tr -d '+' \
		| cut -d '.' -f 1 \
)

case "${temp}" in

	## 0 -> 20°C
	[0-9]|1[0-9]|20)
		icon="${icons[0]}"
		;;

	## 21 -> 39°C
	[2][1-9]|3[0-9])
		icon="${icons[1]}"
		;;

	## 40 -> 59°C
	[4][0-9]|5[0-9])
		icon="${icons[2]}"
		;;

	## 60 -> 79°C
	[6][0-9]|7[0-9])
		icon="${icons[3]}"
		;;

	## 80 -> 100°C
	[8][0-9]|9[0-9]|100)
		icon="${icons[4]}"
		;;

	## unknown °C
	*)
		icon="${icons[5]}"
		;;

esac

echo "${icon}"
