#!/bin/bash
set -euo pipefail

killX() {

	if pidof Xorg>/dev/null; then
		echo 'Press any key to exit...'
		killall Xorg
	fi

}

compile() {

	MAKE_ARGS='-Wnowarn'

	make clean
	make ${MAKE_ARGS}
	make install
	make dist

	echo -e '\e[32mCompilation Done!\e[0m'

	killX

}

compile
