#!/bin/bash
set -euo pipefail

MAKE_ARGS='-Wnowarn'
make clean
make ${MAKE_ARGS}
make install
make dist

echo -e '\e[32mCompilation Done!\e[0m'

if pidof Xorg>/dev/null; then
	echo 'Press any key to exit...'
	killall Xorg
fi

